name: flutter_getx_strategy_pattern
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8

dev_dependencies:
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.6.0